#!/usr/bin/python
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2012 OmniTI Computer Consulting, Inc.  All rights reserved.
# Use is subject to license terms.
#

import os.path
import cherrypy
import re
import time
from cherrypy.process.plugins import DropPrivileges

class Root:
    @cherrypy.expose
    def index(self):
        return """<html>
                <head>
                    <title>Minimal Kayak Install Server</title>
                </head>
                <html>
                <body>
                <h1>Minimal Kayak Install Server</h1>
                </body>
                </html>"""

class KayakLog(object):

    exposed = True

    def PUT(self, macaddr):
        if re.match("^[0-9a-fA-F]{12}$", macaddr) == None:
            raise cherrypy.HTTPError("404 Not Found")
        log = open('/var/kayak/log/' + macaddr + "." + str(time.time()), 'w')
        log.write(cherrypy.request.body.read())

if __name__ == '__main__':
    current_dir = os.path.dirname(os.path.abspath(__file__))
    # Set up site-wide config first so we get a log if errors occur.
    cherrypy.config.update({'environment': 'production',
                            'log.screen': True,
                            'server.socket_host': '0.0.0.0',
                            'server.socket_port': 80,
                           })

    conf = {'/': { 'request.dispatch': cherrypy.dispatch.MethodDispatcher(), },
            '/kayak': {'tools.staticdir.on': True,
                       'tools.staticdir.dir': '/var/kayak/kayak'}}
    root = Root()
    root.kayaklog = KayakLog()
    DropPrivileges(cherrypy.engine, uid=60001, gid=60001).subscribe()
    cherrypy.quickstart(root, '/', config=conf)
